name: Release
on:
  workflow_dispatch:

jobs:
  build:
    name: Manual Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.17.0

      - name: Setup node.js v14.x 
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - run: pnpm install --frozen-lockfile --ignore-scripts=true
      - run: pnpm test:cov
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
