name: Release
on:
  workflow_dispatch:

jobs:
  build:
    name: Manual Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup node.js v14.x 
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
      - run: yarn --ignore-scripts
      - run: yarn test:cov
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
