name: Unit tests
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node.js v14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: yarn

      - name: Install deps
        run: yarn --ignore-scripts

      - name: Run tests
        run: yarn test:cov
